name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      #     cache: 'npm'
      #     cache-dependency-path: hippotech-react/package-lock.json

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        working-directory: ./java-api
        run: mvn -DskipTests=true package

      - name: Release
        uses: djnicholson/release-action@v2.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-name: 'v2.0'
          tag-name: 'v2.0'
          asset-name: 'api.jar'
          file: 'java-api/target/api.jar'
  

      # - name: Start HippoTech server for testing
      #   working-directory: ./java-api
      #   run: ./start.sh

      # - name: Install Cypress
      #   uses: cypress-io/github-action@v4
      #   with:
      #     working-directory: ./hippotech-react
      #     runTests: false

      # - name: Cypress run
      #   uses: cypress-io/github-action@v4
      #   with:
      #     working-directory: ./hippotech-react
      #     install: false
        

      # Test run video was always captured, so this action uses "always()" condition
      # - name: Upload video
      #   uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: cypress-videos
      #     path: hippotech-react/cypress/videos


      # - name: Upload jar
      #   uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: L
      #     path: java-api/logs/hippotech.log

                  