name: CI

permissions:
  contents: write

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: hippotech-react/package-lock.json

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        working-directory: ./java-api
        run: mvn -DskipTests=true package

      - name: Release
        uses: djnicholson/release-action@v2.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-name: 'v2.0'
          tag-name: 'v2.0'
          asset-name: 'api.jar'
          file: 'java-api/target/api.jar'

      - name: Check whether Seeker is enabled
        id: seeker-check
        shell: bash
        run: |
          if [ "${{ secrets.SEEKER_SERVER_URL }}" != '' ]; then
            echo "enabled=true" >> $GITHUB_OUTPUT;
          else
            echo "enabled=false" >> $GITHUB_OUTPUT;
          fi
    
      - name: Add Seeker agent
        if: ${{ steps.seeker-check.outputs.enabled == 'true' }}
        uses: mtolley/seeker-github-actions/download-seeker-agent@v1.1
        with:
          seekerServerUrl: ${{ secrets.SEEKER_SERVER_URL }}
          seekerProjectKey: ${{ secrets.SEEKER_PROJECT_KEY }}
          technology: JAVA
          osFamily: LINUX

      - name: Add Java agent
        if: ${{ steps.seeker-check.outputs.enabled == 'true' }}
        shell: bash
        run: |
          echo "JAVA_TOOL_OPTIONS=-javaagent:`pwd`/seeker/seeker-agent.jar" >> $GITHUB_ENV

      - name: Start HippoTech server for testing
        working-directory: ./java-api
        run: ./start.sh

      - name: Install Cypress
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./hippotech-react
          runTests: false

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./hippotech-react
          install: false
        